# Generated by Django 4.2.5 on 2023-10-02 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookListApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='BookListApi_price_827464_idx',
        ),
    ]
