# Generated by Django 4.2.5 on 2024-01-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookListApi', '0002_remove_book_booklistapi_price_827464_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['price'], name='BookListApi_price_827464_idx'),
        ),
    ]
