# Generated by Django 4.2.5 on 2024-01-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookListApi', '0003_book_booklistapi_price_827464_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='inventory',
            field=models.IntegerField(default=1),
        ),
    ]
